ARG version
FROM almalinux:${version:-8.7}
ARG sudheer="goodboy"
ARG pranavi="sexyboobs"
ENV pranavi=${pranavi}
#RUN echo "sudheer is ${sudheer} vineela is ${vineela} pranavi has ${pranavi} "
CMD ["sleep", "100"]
