name: expense
networks:
  default:
    name: sudheer
volumes:
  simham:
    external: false

services:
  mysql:
    #image: mysql:0.0
    image: sudheer1995/supermysql:5.5
    container_name: mysql
    volumes:
      - source: simham
        target: /var/lib/mysql
        type: volume
  
  backend:
    #image: backend:0.0
    image: sudheer1995/superbackend:5.5
    container_name: backend
    command: sh -c "sleep 35 && node /opt/server/index.js"
    depends_on:
      - mysql
    ports:
      - 8080:8080
  
  frontend:
    #image: frontend:0.0
    image: sudheer1995/superfrontend:5.5
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 80:80